name: Build
on:
    push:
        branches:
            - main
            - release
            - develop
    pull_request:

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                ver: ["Latest", "Lowest"]
        name: PHP ${{ matrix.php }} ${{ matrix.ver }} Unit Test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - if: ${{ matrix.ver == 'Latest' }}
              name: Install Dependencies (Latest)
              run: composer update --no-interaction
            - if: ${{ matrix.ver == 'Lowest' }}
              name: Install Dependencies (Lowest)
              run: composer update --no-interaction --prefer-lowest
            - name: Run Script
              run: composer phpunit

    phpcs:
        runs-on: ubuntu-latest
        name: PHP Style Check
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.0"
            - name: Install Dependencies
              run: composer update --no-interaction
            - name: Run Script
              run: composer phpcs

    phpstan:
        runs-on: ubuntu-latest
        name: PHP Static Analysis
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.0"
            - name: Install Dependencies
              run: composer update --no-interaction
            - name: Run Script
              run: composer phpstan
