name: Build Docs
on:
    workflow_dispatch

jobs:
    phpdoc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Update Wiki
              uses: impresscms-dev/phpdocs-wiki-update-action@v2.2.5
              with:
                  engine: clean/phpdoc-md
                  class_root_namespace: ShineUnited\\WordPress\\Hooks
                  include: src/**
